steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'slackevent', '--trigger-http', '--runtime', 'go111', '--entry-point', 'SlackEvent', '--source', './slackevent']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'slackmessage', '--trigger-topic', 'slack.message', '--runtime', 'go111', '--entry-point', 'Record', '--source', './slackmessage']
